# Generated by Django 5.2.8 on 2026-05-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Leptis Group', max_length=200)),
                ('established_year', models.CharField(default='2016', max_length=10)),
                ('employee_count', models.CharField(default='100+', max_length=50)),
                ('verticals_count', models.CharField(default='4+', max_length=50)),
                ('about_title', models.CharField(default='Delivering Quality, Trust, and Modern Convenience', max_length=255)),
                ('about_narrative_1', models.TextField(default="Founded in 2016 in the United Arab Emirates, Leptis Group originated as a strategic expansion of Abreco Freight's logistics and trading operations. Since our inception, we have systematically diversified across sectors including international trading, exports, fresh agricultural produce supply, and modern retail supermarkets.")),
                ('about_narrative_2', models.TextField(default='Today, with extensive operations in the UAE and India, we are recognized for our unwavering reliability, global connectivity, and strict adherence to international quality standards. We believe every consumer deserves accessible, high-quality, and modern experiences, which we strive to deliver every day.')),
                ('careers_title', models.CharField(default='Careers at Leptis', max_length=255)),
                ('careers_description', models.TextField(default='Join our growing team of dedicated professionals and build a rewarding career at Leptis Group.')),
                ('careers_email_recipient', models.EmailField(default='leptisgroupsit@gmail.com', max_length=254)),
                ('contact_email', models.EmailField(default='info@leptisgroups.com', max_length=254)),
                ('contact_phone', models.CharField(default='+971 4 250 5549', max_length=50)),
                ('contact_address', models.TextField(default='Al Jazeera Al Hamra, Ras Al Khaimah, UAE')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.AddField(
            model_name='offer',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
