# Generated by Django 5.2.8 on 2026-05-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_sitesettings_offer_expire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='about_team_img',
            field=models.ImageField(blank=True, null=True, upload_to='settings/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='consult_img',
            field=models.ImageField(blank=True, null=True, upload_to='settings/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_bg',
            field=models.ImageField(blank=True, null=True, upload_to='settings/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='home_about_img',
            field=models.ImageField(blank=True, null=True, upload_to='settings/'),
        ),
    ]
