# Generated by Django 5.2.8 on 2026-05-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_brandlogo_project_projectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='copyright_text',
            field=models.CharField(default='Leptis Group. All rights reserved.', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_url',
            field=models.CharField(default='https://www.facebook.com/share/19u51ph8vv/', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_about_text',
            field=models.TextField(default='Leptis Group, founded in 2016 in the UAE, has evolved into a multi-sector enterprise covering logistics, trading, exports, and retail. Our commitment to quality and customer satisfaction defines everything we do.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_btn1_text',
            field=models.CharField(default='Partner With Us', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_btn2_text',
            field=models.CharField(default='Discover More', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_description',
            field=models.TextField(default="Take your operations to the next level with Leptis Group's global expertise spanning Logistics, International Trading, Retail Supermarkets, and Fresh Agricultural Sourcing."),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title',
            field=models.CharField(default='Advancing Growth Through Innovative & Trusted Solutions', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_url',
            field=models.CharField(default='#', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='linkedin_url',
            field=models.CharField(default='#', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twitter_url',
            field=models.CharField(default='#', max_length=500),
        ),
    ]
