# Generated by Django 5.2.8 on 2026-05-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_sitesettings_copyright_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(default='Our Winning Team', max_length=255)),
                ('image', models.ImageField(upload_to='team/')),
                ('facebook_url', models.CharField(blank=True, default='#', max_length=500)),
                ('twitter_url', models.CharField(blank=True, default='#', max_length=500)),
                ('youtube_url', models.CharField(blank=True, default='#', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
