# Generated by Django 5.2.8 on 2026-06-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0006_teammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='expire_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
