# Generated by Django 5.2.8 on 2026-06-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0008_create_default_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='careers_bg',
            field=models.ImageField(blank=True, null=True, upload_to='settings/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='position',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
