# Generated by Django 5.2.8 on 2026-06-12 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0009_sitesettings_careers_bg_alter_teammember_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Offer',
            new_name='Event',
        ),
        migrations.CreateModel(
            name='EventPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='events/pdfs/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='events/thumbnails/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='offers.event')),
            ],
        ),
        migrations.DeleteModel(
            name='OfferPDF',
        ),
    ]
