# Generated by Django 5.2.8 on 2026-06-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0010_rename_offer_event_eventpdf_delete_offerpdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('dubai_lassi_home', 'DUBAI - LASSI HOME SHOP'), ('rak_hamrah', 'RAK - LEPTIS SHOPPING CENTER AL HAMRAH'), ('rak_marjan', 'RAK - LEPTIS SUPERMARKET MARJAN'), ('alain_spicy', 'AL AIN - SPICY VILLAGE AL AIN'), ('alain_leptis', 'AL AIN - LEPTIS SHOPPING CENTER AL AIN')], default='dubai_lassi_home', max_length=50),
        ),
    ]
