# Generated by Django 5.2.8 on 2026-06-12 10:33

from django.db import migrations, models

def populate_default_branches(apps, schema_editor):
    Branch = apps.get_model('offers', 'Branch')
    defaults = [
        ("dubai_lassi_home", "DUBAI - LASSI HOME SHOP"),
        ("rak_hamrah", "RAK - LEPTIS SHOPPING CENTER AL HAMRAH"),
        ("rak_marjan", "RAK - LEPTIS SUPERMARKET MARJAN"),
        ("alain_spicy", "AL AIN - SPICY VILLAGE AL AIN"),
        ("alain_leptis", "AL AIN - LEPTIS SHOPPING CENTER AL AIN"),
    ]
    for key, name in defaults:
        Branch.objects.get_or_create(key=key, name=name)

def remove_default_branches(apps, schema_editor):
    Branch = apps.get_model('offers', 'Branch')
    Branch.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0011_project_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(default='dubai_lassi_home', max_length=100),
        ),
        migrations.RunPython(populate_default_branches, reverse_code=remove_default_branches),
    ]
