# Generated by Django 5.2.8 on 2026-06-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0012_add_branch_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='brands_bg',
            field=models.ImageField(blank=True, null=True, upload_to='settings/'),
        ),
    ]
