# Generated by Django 5.2.8 on 2026-06-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0013_sitesettings_brands_bg'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='site_signature',
            field=models.CharField(blank=True, default='ibill software solutions llc', max_length=255, null=True),
        ),
    ]
