# Generated by Django 5.2.8 on 2026-06-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0015_adminotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('reason', models.CharField(blank=True, default='Manual block', max_length=255)),
                ('blocked_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FailedLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('username', models.CharField(blank=True, max_length=150)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
