# Generated by Django 5.2.8 on 2026-06-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0016_blockedip_failedloginattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='founder_image',
            field=models.ImageField(blank=True, null=True, upload_to='settings/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='founder_name',
            field=models.CharField(default='Ahamed Remil', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='founder_quote',
            field=models.TextField(default="True business leadership isn't just about expansion; it's about building a trusted legacy of innovation, inclusivity, and long-term value for every community we serve."),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='founder_title',
            field=models.CharField(default='Founder & Chairman', max_length=255),
        ),
    ]
