# Generated by Django 5.2.8 on 2026-06-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0018_businessvertical_strength_timelinemilestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description',
            field=models.TextField(default='Leptis Group - Logistics, Global Trading, Supermarkets & Fresh Produce'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_keywords',
            field=models.CharField(default='leptis, leptis group, logistics, trading, supermarket, fresh produce', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_title',
            field=models.CharField(default='Leptis Group', max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='share_image',
            field=models.ImageField(blank=True, null=True, upload_to='settings/'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_logo',
            field=models.ImageField(blank=True, null=True, upload_to='settings/'),
        ),
    ]
